ERROR - 2022-05-08 00:24:29 --> Table 'ci4lombi.users' doesn't exist
CRITICAL - 2022-05-08 00:24:29 --> Table 'ci4lombi.users' doesn't exist
#0 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('admin', 'username', Array, NULL)
#6 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('username', 'username', 'admin', Array, Array)
#7 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\ci4rpl\app\Controllers\Auth.php(12): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Auth->register()
#10 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4rpl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-05-08 00:25:41 --> Table 'ci4lombi.users' doesn't exist
CRITICAL - 2022-05-08 00:25:41 --> Table 'ci4lombi.users' doesn't exist
#0 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\ci4rpl\app\Controllers\Auth.php(33): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Auth->register()
#9 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4rpl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-05-08 02:00:58 --> Unknown column 'created_at' in 'field list'
CRITICAL - 2022-05-08 02:00:58 --> Unknown column 'created_at' in 'field list'
#0 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\ci4rpl\app\Controllers\Auth.php(36): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Auth->register()
#9 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\ci4rpl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-05-08 02:13:26 --> Undefined constant Config\Services::validation
#0 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Daftar->index()
#1 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Daftar))
#2 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4rpl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-08 02:25:38 --> Class "App\Models\AuthModel" not found
#0 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4rpl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-05-08 02:39:08 --> Undefined property: stdClass::$level
#0 C:\xampp\htdocs\ci4rpl\app\Controllers\Auth.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 58)
#1 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Auth->login()
#2 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4rpl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-05-08 02:55:16 --> Declaration of App\Filters\AuthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-08 02:55:17 --> Declaration of App\Filters\AuthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-05-08 02:57:25 --> Class "Config\App\Filters\AuthFilter" not found
#0 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\Filters\Filters->run('/', 'after')
#1 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\ci4rpl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-05-08 02:58:30 --> Declaration of App\Filters\AuthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
